var data = `{
	"Skins":{
        "Conqueror":["Default","Christmas 1","Christmas 2"],
        "AMX 50 100":["Default"],
        "Van Helsing":["Default"],
        "Type 62":["Default", "Dragon", "Dragon Gold"],
        "Tetrarch":["Default"],
        "Dicker Max":["Default"]
    },
    "Tanks":["Conqueror","AMX 50 100", "Van Helsing", "Type 62", "Tetrarch", "Dicker Max"]
} `;
var data_full = `{
	"Tanks":{
        "Conqueror":{
            "path_textures":"Conqueror_textures/",
            "path_meshes":"Conqueror_meshes/",
            "head":{
                "mesh":[
                    "1_hull_batch_0.obj",
                    "1_gun_01_batch_0.obj",
                    "1_gun_03_batch_0.obj",
                    "1_gun_05_batch_0.obj",
                    "1_gun_06_batch_0.obj",
                    "1_gun_07_batch_0.obj",
                    "1_turret_01_batch_0.obj",
                    "1_turret_02_batch_0.obj"],
                "textures":{
                    "Default":{"file":"Conqueror.png", "params":""},
                    "Christmas 1":{"file":"common_01.mali.png", "params":"parameters"},
                    "Christmas 2":{"file":"common_02.mali.png", "params":"parameters"}
                }},
            "tracks":{
                "mesh":[
                    "1_chassis_wheel_L_01_batch_0.obj",
                    "1_chassis_wheel_L_02_batch_0.obj",
                    "1_chassis_wheel_L_03_batch_0.obj",
                    "1_chassis_wheel_L_04_batch_0.obj",
                    "1_chassis_wheel_L_05_batch_0.obj",
                    "1_chassis_wheel_L_06_batch_0.obj",
                    "1_chassis_wheel_L_07_batch_0.obj",
                    "1_chassis_wheel_L_08_batch_0.obj",
                    "1_chassis_wheel_L_09_batch_0.obj",
                    "1_chassis_wheel_L_10_batch_0.obj",
                    "1_chassis_wheel_R_01_batch_0.obj",
                    "1_chassis_wheel_R_02_batch_0.obj",
                    "1_chassis_wheel_R_03_batch_0.obj",
                    "1_chassis_wheel_R_04_batch_0.obj",
                    "1_chassis_wheel_R_05_batch_0.obj",
                    "1_chassis_wheel_R_06_batch_0.obj",
                    "1_chassis_wheel_R_07_batch_0.obj",
                    "1_chassis_wheel_R_08_batch_0.obj",
                    "1_chassis_wheel_R_09_batch_0.obj",
                    "1_chassis_wheel_R_10_batch_0.obj",
                    "1_chassis_track_L_batch_0.obj",
                    "1_chassis_track_R_batch_0.obj"
                ],
                "textures":{"default":"Conqueror_Tracks.png"}}
        },
"AMX 50 100":{
            "path_textures":"AMX_50_100.sc2_textures/",  
            "path_meshes":"AMX_50_100.sc2_meshes/",
            "head":{
                "mesh":[
"1_gun_01_batch_1.obj",
"1_gun_02_batch_1.obj",
"1_gun_03_batch_1.obj",
"1_HP_Fire_01_batch_0.obj",
"1_HP_Fire_02_batch_0.obj",
"1_HP_gui_batch_0.obj",
"1_HP_gunFire_01_batch_0.obj",
"1_HP_gunFire_02_batch_0.obj",
"1_HP_gunFire_03_batch_0.obj",
"1_hull_batch_1.obj",
"1_turret_01_batch_1.obj"
                ],
                "textures":{
                    "Default":{"file":"AMX_50_100.mali.png", "params":""}
                }},
            "tracks":{
                "mesh":[
"1_chassis_track_L_batch_1.obj",
"1_chassis_track_R_batch_1.obj",
"1_chassis_wheel_L_01_batch_0.obj",
"1_chassis_wheel_L_02_batch_0.obj",
"1_chassis_wheel_L_03_batch_0.obj",
"1_chassis_wheel_L_04_batch_0.obj",
"1_chassis_wheel_L_05_batch_0.obj",
"1_chassis_wheel_L_06_batch_0.obj",
"1_chassis_wheel_L_07_batch_0.obj",
"1_chassis_wheel_L_08_batch_0.obj",
"1_chassis_wheel_L_09_batch_0.obj",
"1_chassis_wheel_L_10_batch_0.obj",
"1_chassis_wheel_L_11_batch_0.obj",
"1_chassis_wheel_L_12_batch_0.obj",
"1_chassis_wheel_L_13_batch_0.obj",
"1_chassis_wheel_L_14_batch_0.obj",
"1_chassis_wheel_L_15_batch_0.obj",
"1_chassis_wheel_L_16_batch_0.obj",
"1_chassis_wheel_R_01_batch_0.obj",
"1_chassis_wheel_R_02_batch_0.obj",
"1_chassis_wheel_R_03_batch_0.obj",
"1_chassis_wheel_R_04_batch_0.obj",
"1_chassis_wheel_R_05_batch_0.obj",
"1_chassis_wheel_R_06_batch_0.obj",
"1_chassis_wheel_R_07_batch_0.obj",
"1_chassis_wheel_R_08_batch_0.obj",
"1_chassis_wheel_R_09_batch_0.obj",
"1_chassis_wheel_R_10_batch_0.obj",
"1_chassis_wheel_R_11_batch_0.obj",
"1_chassis_wheel_R_12_batch_0.obj",
"1_chassis_wheel_R_13_batch_0.obj",
"1_chassis_wheel_R_14_batch_0.obj",
"1_chassis_wheel_R_15_batch_0.obj",
"1_chassis_wheel_R_16_batch_0.obj",
"1_HP_Track_Exhaus_01_batch_0.obj",
"1_HP_Track_Exhaus_02_batch_0.obj",
"1_HP_Track_LFront_batch_0.obj",
"1_HP_Track_LRear_batch_0.obj",
"1_HP_Track_RFront_batch_0.obj",
"1_HP_Track_RRear_batch_0.obj",
"1_HP_TrackUp_LFront_batch_0.obj",
"1_HP_TrackUp_LRear_batch_0.obj",
"1_HP_TrackUp_RFront_batch_0.obj",
"1_HP_TrackUp_RRear_batch_0.obj"
                ],
                "textures":{"default":"AMX_track.mali.png"}}
        },
"Van Helsing":{
            "path_textures":"Van_Helsing.sc2_textures/",  
            "path_meshes":"Van_Helsing.sc2_meshes/",
            "head":{
                "mesh":[
"1_gun_01_batch_1.obj",
"1_HP_Custom_gun_01_batch_0.obj",
"1_HP_Custom_hull_01_batch_0.obj",
"1_HP_Custom_hull_02_batch_0.obj",
"1_HP_Custom_hull_03_batch_0.obj",
"1_HP_Fire_01_batch_0.obj",
"1_HP_Fire_02_batch_0.obj",
"1_HP_gui_batch_0.obj",
"1_HP_gunFire_01_batch_0.obj",
"1_hull_batch_1.obj",
"1_turret_01_batch_1.obj"
                ],
                "textures":{
                    "Default":{"file":"Van_Helsing.mali.png", "params":""}
                }},
            "tracks":{
                "mesh":[
"1_chassis_track_L_batch_1.obj",
"1_chassis_track_R_batch_1.obj",
"1_chassis_wheel_L_01_batch_0.obj",
"1_chassis_wheel_L_02_batch_0.obj",
"1_chassis_wheel_L_03_batch_0.obj",
"1_chassis_wheel_L_04_batch_0.obj",
"1_chassis_wheel_L_05_batch_0.obj",
"1_chassis_wheel_L_06_batch_0.obj",
"1_chassis_wheel_L_07_batch_0.obj",
"1_chassis_wheel_L_08_batch_0.obj",
"1_chassis_wheel_L_09_batch_0.obj",
"1_chassis_wheel_L_10_batch_0.obj",
"1_chassis_wheel_L_11_batch_0.obj",
"1_chassis_wheel_L_12_batch_0.obj",
"1_chassis_wheel_R_01_batch_0.obj",
"1_chassis_wheel_R_02_batch_0.obj",
"1_chassis_wheel_R_03_batch_0.obj",
"1_chassis_wheel_R_04_batch_0.obj",
"1_chassis_wheel_R_05_batch_0.obj",
"1_chassis_wheel_R_06_batch_0.obj",
"1_chassis_wheel_R_07_batch_0.obj",
"1_chassis_wheel_R_08_batch_0.obj",
"1_chassis_wheel_R_09_batch_0.obj",
"1_chassis_wheel_R_10_batch_0.obj",
"1_chassis_wheel_R_11_batch_0.obj",
"1_chassis_wheel_R_12_batch_0.obj",
"1_HP_Track_Exhaus_01_batch_0.obj",
"1_HP_Track_Exhaus_02_batch_0.obj",
"1_HP_Track_LFront_batch_0.obj",
"1_HP_Track_LRear_batch_0.obj",
"1_HP_Track_RFront_batch_0.obj",
"1_HP_Track_RRear_batch_0.obj",
"1_HP_TrackUp_LFront_batch_0.obj",
"1_HP_TrackUp_LRear_batch_0.obj",
"1_HP_TrackUp_RFront_batch_0.obj",
"1_HP_TrackUp_RRear_batch_0.obj"
                ],
                "textures":{"default":"AMX_track.mali.png"}}
        },
"Type 62":{
            "path_textures":"Type62.sc2_textures/",  
            "path_meshes":"Type62.sc2_meshes/",
            "head":{
                "mesh":[
"1_gun_01_batch_0.obj",
"1_HP_Fire_01_batch_0.obj",
"1_HP_Fire_02_batch_0.obj",
"1_HP_gui_batch_0.obj",
"1_HP_gunFire_01_batch_0.obj",
"1_hull_batch_0.obj",
"1_turret_01_batch_0.obj"
                ],
                "textures":{
                    "Default":{"file":"Type62.mali.png", "params":""},
                    "Dragon":{"file":"Type62_dragon.mali.png", "params":""},
                    "Dragon Gold":{"file":"Type62_dragon_gold.mali.png", "params":""}
                }},
            "tracks":{
                "mesh":[
"1_chassis_track_L_batch_0.obj",
"1_chassis_track_R_batch_0.obj",
"1_chassis_wheel_L_01_batch_0.obj",
"1_chassis_wheel_L_02_batch_0.obj",
"1_chassis_wheel_L_03_batch_0.obj",
"1_chassis_wheel_L_04_batch_0.obj",
"1_chassis_wheel_L_05_batch_0.obj",
"1_chassis_wheel_L_06_batch_0.obj",
"1_chassis_wheel_L_07_batch_0.obj",
"1_chassis_wheel_R_01_batch_0.obj",
"1_chassis_wheel_R_02_batch_0.obj",
"1_chassis_wheel_R_03_batch_0.obj",
"1_chassis_wheel_R_04_batch_0.obj",
"1_chassis_wheel_R_05_batch_0.obj",
"1_chassis_wheel_R_06_batch_0.obj",
"1_chassis_wheel_R_07_batch_0.obj",
"1_HP_Track_Exhaus_1_batch_0.obj",
"1_HP_Track_LFront_batch_0.obj",
"1_HP_Track_LRear_batch_0.obj",
"1_HP_Track_RFront_batch_0.obj",
"1_HP_Track_RRear_batch_0.obj",
"1_HP_TrackUp_LFront_batch_0.obj",
"1_HP_TrackUp_LRear_batch_0.obj",
"1_HP_TrackUp_RFront_batch_0.obj",
"1_HP_TrackUp_RRear_batch_0.obj"
                ],
                "textures":{"default":"Type62_track.mali.png"}}
        },
"Tetrarch":{
            "path_textures":"Tetrarch_LL.sc2_textures/",  
            "path_meshes":"Tetrarch_LL.sc2_meshes/",
            "head":{
                "mesh":[
"1_gun_01_batch_1.obj",
"1_HP_Fire_01_batch_0.obj",
"1_HP_Fire_02_batch_0.obj",
"1_HP_gui_batch_0.obj",
"1_HP_gunFire_01_batch_0.obj",
"1_hull_batch_1.obj",
"1_turret_01_batch_1.obj"
                ],
                "textures":{
                    "Default":{"file":"Tetrarch_LL.mali.png", "params":""}
                }},
            "tracks":{
                "mesh":[
"1_chassis_track_L_batch_1.obj",
"1_chassis_track_R_batch_1.obj",
"1_chassis_wheel_L_01_batch_0.obj",
"1_chassis_wheel_L_02_batch_0.obj",
"1_chassis_wheel_L_03_batch_0.obj",
"1_chassis_wheel_L_04_batch_0.obj",
"1_chassis_wheel_R_01_batch_0.obj",
"1_chassis_wheel_R_02_batch_0.obj",
"1_chassis_wheel_R_03_batch_0.obj",
"1_chassis_wheel_R_04_batch_0.obj",
"1_HP_Track_Exhaus_01_batch_0.obj",
"1_HP_Track_Exhaus_02_batch_0.obj",
"1_HP_Track_LFront_batch_0.obj",
"1_HP_Track_LRear_batch_0.obj",
"1_HP_Track_RFront_batch_0.obj",
"1_HP_Track_RRear_batch_0.obj",
"1_HP_TrackUp_LFront_batch_0.obj",
"1_HP_TrackUp_LRear_batch_0.obj",
"1_HP_TrackUp_RFront_batch_0.obj",
"1_HP_TrackUp_RRear_batch_0.obj"
                ],
                "textures":{"default":"Tetrarch_LL_tarck.mali.png"}}
        },
"Dicker Max":{
            "path_textures":"/DickerMax.sc2_textures/",  
            "path_meshes":"/DickerMax.sc2_meshes/",
            "head":{
                "mesh":[
"1_gun_03_batch_0.obj",
"1_HP_Fire_01_batch_0.obj",
"1_HP_Fire_02_batch_0.obj",
"1_HP_gui_batch_0.obj",
"1_HP_gunFire_03_batch_0.obj",
"1_hull_batch_0.obj",
"1_turret_01_batch_0.obj"
                ],
                "textures":{
                    "Default":{"file":"DickerMax.mali.png", "params":""}
                }},
            "tracks":{
                "mesh":[
"1_chassis_track_L_batch_0.obj",
"1_chassis_track_R_batch_0.obj",
"1_chassis_wheel_L_01_batch_0.obj",
"1_chassis_wheel_L_02_batch_0.obj",
"1_chassis_wheel_L_03_batch_0.obj",
"1_chassis_wheel_L_04_batch_0.obj",
"1_chassis_wheel_L_05_batch_0.obj",
"1_chassis_wheel_L_06_batch_0.obj",
"1_chassis_wheel_L_07_batch_0.obj",
"1_chassis_wheel_L_08_batch_0.obj",
"1_chassis_wheel_L_09_batch_0.obj",
"1_chassis_wheel_L_10_batch_0.obj",
"1_chassis_wheel_L_11_batch_0.obj",
"1_chassis_wheel_L_12_batch_0.obj",
"1_chassis_wheel_L_13_batch_0.obj",
"1_chassis_wheel_L_14_batch_0.obj",
"1_chassis_wheel_R_01_batch_0.obj",
"1_chassis_wheel_R_02_batch_0.obj",
"1_chassis_wheel_R_03_batch_0.obj",
"1_chassis_wheel_R_04_batch_0.obj",
"1_chassis_wheel_R_05_batch_0.obj",
"1_chassis_wheel_R_06_batch_0.obj",
"1_chassis_wheel_R_07_batch_0.obj",
"1_chassis_wheel_R_08_batch_0.obj",
"1_chassis_wheel_R_09_batch_0.obj",
"1_chassis_wheel_R_10_batch_0.obj",
"1_chassis_wheel_R_11_batch_0.obj",
"1_chassis_wheel_R_12_batch_0.obj",
"1_chassis_wheel_R_13_batch_0.obj",
"1_chassis_wheel_R_14_batch_0.obj",
"1_HP_Track_LFront_batch_0.obj",
"1_HP_Track_LRear_batch_0.obj",
"1_HP_Track_RFront_batch_0.obj",
"1_HP_Track_RRear_batch_0.obj",
"1_HP_TrackUp_LFront_batch_0.obj",
"1_HP_TrackUp_LRear_batch_0.obj",
"1_HP_TrackUp_RFront_batch_0.obj",
"1_HP_TrackUp_RRear_batch_0.obj"
                ],
                "textures":{"default":"Vickers_track.mali.png"}}
        }
    }} `;
